[package]
name = "p2p"
version = "0.1.0"
authors = ["Mikhail Hasso <mihasso@protonmail.com>"]
edition = "2018"

[[bin]]
name = "daemon"
path = "src/daemon.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[dependencies]
serde = "1.0.101"
serde_json = "1.0.41"
serde_derive = "1.0.101"
