[workspace]
members = ["crates/core", "crates/daemon", "crates/cli"]

[profile.release]
lto = "thin"
codegen-units = 1
resolver = "3"   # use the 2024 resolver

[workspace.dependencies]
clap = "2.33.0"
serde = "1.0.101"
serde_json = "1.0.41"
serde_derive = "1.0.101"
rand = "0.7.2"
threadpool = "1.7.1"
